language: csharp
solution: ClassBuilder.sln
install:
  - nuget restore ClassBuilder.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release ClassBuilder.sln
  - nunit-console ./ClassBuilder.FS.NUnit/bin/Release/ClassBuilder.NUnit.dll